SELECT t2.NOME_FORNECEDOR, t3.PRECO FROM FORNECIMENTO AS t1
INNER JOIN (FORNECEDOR AS t2, PEÇA AS t3, CARRO AS t4)
ON (
	t1.CODIGO_FORNECEDOR = t2.CODIGO_FORNECEDOR AND
    t1.CODIGO_PEÇA = t3.CODIGO_PEÇA AND
    t1.CODIGO_CARRO = t4.CODIGO_CARRO
)
WHERE t2.cidade = "VITORIA" AND
t3.CODIGO_PEÇA = "MOTOR" AND
t4.CODIGO_CARRO = "KOMBI";
